urlrouter.urlrouter_entity.*:
  type: config_entity
  label: 'URL Router config'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
    source:
      type: string
      label: 'Source'
    destination:
      type: string
      label: 'Destination'
    permanent:
      type: boolean
      label: 'Permanent'
